### ISSUE TITLE
Initializes an object from braced-init-list

### ISSUE THREAD

**Issue by Kvaz1r** [ilmola/gml#2]
Since the library for C++11 will be good add constructor for an object with initializer list. Now need use C-array or temporary std::vector:

```
gml::mat<int,2,2> test({1,1,1,1},false); //<-compile-time error
gml::mat<int,4,1> result(std::vector<int>{0,0,1,1}.data(),true);//<- work, but unconvenient
```

**Comment by ilmola** [comment]
Closing this old issue as initializer list would mess up constructor overloads.
